name: Deploy Gotenberg (PDF)
on:
  push:
    paths:
      - gotenberg/**
      - .nais/nais-dev-gotenberg.yaml
      - .nais/nais-prod-gotenberg.yaml
    branches:
      - main
      - dev/better-pdf

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tsm
          image_suffix: gotenberg
          docker_context: gotenberg
          salsa: false
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
      digest: ${{ steps.docker-build-push.outputs.digest }}

  sbom:
    name: Upload SBOM for build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: navikt/tsm-workflows/actions/attest-sign@main
        with:
          image: ${{ needs.build.outputs.image }}
          digest: ${{ needs.build.outputs.digest }}
          team: tsm

  deploy-gotenberg-dev:
    name: Deploy Gotenberg to dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais-dev-gotenberg.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}

  deploy-gotenberg-prod:
    if: github.ref_name == 'main'
    name: Deploy Gotenberg to prod
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais-prod-gotenberg.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
